spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

security:
  access:
    enforce: ${ACCESS_CONTROL_ENFORCE:true}
    require-authentication: ${ACCESS_CONTROL_REQUIRE_AUTH:true}
